
import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'man-matters-shampoo',
    title: 'Man Matters DHT Blocker Hair Strengthening Shampoo',
    category: 'Self Care',
    price: 12.99,
    image: '',
    description: 'A science-backed solution for thinning hair. This DHT blocker shampoo uses Biotin and Argan oil to strengthen follicles from the root. It’s become a mandatory part of our morning ritual for noticeable density.',
    rating: 4.7,
    reviews: 5200,
    affiliateUrl: 'https://amzn.to/3YFuWtj',
    tags: ['Daily Routine', 'Hair Health'],
    solution: 'DHT Blocker Shampoo'
  },
  {
    id: 'kids-printer',
    title: 'Instant Inkless Drawing Sticker Printer',
    category: 'Gadgets',
    price: 69.99,
    image: '',
    description: 'Perfect solution for kids drawings. This ink-less printer turns phone photos into physical stickers in seconds. Great for scrapbooking every single day—a true Daily Essential.',
    rating: 4.8,
    reviews: 1450,
    affiliateUrl: 'https://amazon.com',
    tags: ['Must Have for Parents', 'Creative'],
    solution: 'Phomemo M02 pocket printer'
  },
  {
    id: 'speaker-cleaner',
    title: 'Professional Phone & Speaker Deep Cleaning Kit',
    category: 'Daily Needs',
    price: 12.99,
    image: '',
    description: 'Muffled sound? Most people think their phone is broken when it is just dust. This 7-in-1 tool gets into every crack. It saved my AirPods last week and is now a desk staple.',
    rating: 4.9,
    reviews: 2100,
    affiliateUrl: 'https://amazon.com',
    tags: ['Tech Hack', 'Best Seller'],
    solution: 'Electronics Cleaning Kit'
  },
  {
    id: 'water-bottle',
    title: 'Smart Smart Tracking Hydration Bottle',
    category: 'Daily Needs',
    price: 35.00,
    image: '',
    description: 'It glows when you have not taken a sip in an hour. Simple, effective, and helps you stay hydrated without thinking about it.',
    rating: 4.6,
    reviews: 890,
    affiliateUrl: 'https://amazon.com',
    tags: ['Health'],
    solution: 'Hidrate Spark smart water bottle'
  },
  {
    id: 'wake-light',
    title: 'Natural Sunrise Wake-Up Alarm Lamp',
    category: 'Home',
    price: 49.99,
    image: '',
    description: 'Waking up to light instead of a screaming phone changed my mood entirely. It mimics a natural sunrise over 30 minutes.',
    rating: 4.7,
    reviews: 3200,
    affiliateUrl: 'https://amazon.com',
    tags: ['Sleep Tech'],
    solution: 'Philips Sunrise Alarm Clock'
  },
  {
    id: 'cable-mgmt',
    title: 'Magnetic Cable Management Desktop Organizers',
    category: 'Workspace',
    price: 15.50,
    image: '',
    description: 'Cables falling behind the desk are a nightmare. These magnets keep them exactly where you need them. Clean desk, clean mind.',
    rating: 4.8,
    reviews: 560,
    affiliateUrl: 'https://amazon.com',
    tags: ['Productivity'],
    solution: 'Anker Magnetic Cable Organizer'
  },
  {
    id: 'car-vacuum',
    title: 'High-Power Handheld Mini Car Vacuum',
    category: 'Daily Needs',
    price: 29.99,
    image: '',
    description: 'It is smaller than a water bottle but has enough suction to clean up after the kids in the backseat. Fits in the glove box.',
    rating: 4.5,
    reviews: 1100,
    affiliateUrl: 'https://amazon.com',
    tags: ['Car Care'],
    solution: 'Handheld Portable Car Vacuum'
  },
  {
    id: 'key-finder',
    title: 'Bluetooth Item & Key Finder Tracker',
    category: 'Gadgets',
    price: 24.00,
    image: '',
    description: 'I used to spend 10 minutes every morning looking for my keys. Now I just ping them from my phone. A literal life saver.',
    rating: 4.9,
    reviews: 8500,
    affiliateUrl: 'https://amazon.com',
    tags: ['Essentials'],
    solution: 'Tile Mate Bluetooth Tracker'
  },
  {
    id: 'milk-frother',
    title: 'Electric Handheld Milk & Coffee Frother',
    category: 'Kitchen',
    price: 9.99,
    image: '',
    description: 'Turn a basic cup of coffee into a cafe-style latte in 15 seconds. It is the cheapest luxury you can buy for your kitchen.',
    rating: 4.7,
    reviews: 12000,
    affiliateUrl: 'https://amazon.com',
    tags: ['Coffee Lovers'],
    solution: 'Zulay Kitchen Milk Frother'
  },
  {
    id: 'screen-cleaner',
    title: 'Mist Spray Microfiber Screen Cleaner',
    category: 'Daily Needs',
    price: 11.00,
    image: '',
    description: 'The microfiber wrap is built into the bottle. Spray and wipe. No more oily smudges on your iPad or laptop.',
    rating: 4.8,
    reviews: 430,
    affiliateUrl: 'https://amazon.com',
    tags: ['Clean Tech'],
    solution: 'Screen Cleaner Spray with Cloth'
  },
  {
    id: 'bag-sealer',
    title: 'Portable Mini Heat Sealer for Food Bags',
    category: 'Kitchen',
    price: 14.99,
    image: '',
    description: 'Forget clips that fall off. This seals the plastic bag shut again. Keeps chips and cereal fresh for weeks.',
    rating: 4.4,
    reviews: 720,
    affiliateUrl: 'https://amazon.com',
    tags: ['Kitchen Hack'],
    solution: 'Mini Bag Sealer Heat Seal'
  },
  {
    id: 'furniture-sliders',
    title: 'Heavy-Duty Reusable Furniture Sliders',
    category: 'Home',
    price: 13.99,
    image: '',
    description: 'The ultimate solution for rearranging rooms alone. These allow 300lb cabinets to glide over carpet like ice.',
    rating: 4.9,
    reviews: 4500,
    affiliateUrl: 'https://amazon.com',
    tags: ['Moving', 'Home Improvement'],
    solution: 'Furniture Sliders for Hardwood and Carpet'
  },
  {
    id: 'desk-mat',
    title: 'Anti-Slip Felt Desk Protector & Mat',
    category: 'Workspace',
    price: 22.00,
    image: '',
    description: 'Protects your desk and improves mouse tracking. High-quality felt that adds a layer of warmth to any glass or wood surface.',
    rating: 4.7,
    reviews: 1200,
    affiliateUrl: 'https://amazon.com',
    tags: ['Aesthetic', 'Workspace'],
    solution: 'Large Felt Desk Pad'
  },
  {
    id: 'veg-chopper',
    title: '12-in-1 Professional Vegetable Chopper',
    category: 'Kitchen',
    price: 27.99,
    image: '',
    description: 'Reduces meal prep time from 20 minutes to 2. Uniform cuts every time. Essential for anyone who cooks at home daily.',
    rating: 4.8,
    reviews: 18000,
    affiliateUrl: 'https://amazon.com',
    tags: ['Cooking', 'Efficiency'],
    solution: 'Fullstar Vegetable Chopper'
  },
  {
    id: 'treadmill-lubricant',
    title: '100% Silicone Treadmill Belt Lubricant',
    category: 'Home',
    price: 14.50,
    image: '',
    description: 'Prevents expensive motor repairs. A 30-second application every month keeps your home gym running silent.',
    rating: 4.9,
    reviews: 3100,
    affiliateUrl: 'https://amazon.com',
    tags: ['Fitness', 'Maintenance'],
    solution: 'Spot On Treadmill Silicone Lubricant'
  }
];
